"""Render the Phase 4 comparison as a terminal table and a markdown report.

The acceptance bar (PROJECT_SPEC.md §4 Phase 4) is that someone who has not
read the code can read the report and understand what happened and why. So
every row carries a mechanism sentence, not just a pass/fail mark — "isolated
didn't leak" is a result; "the Executor only read two enum fields" is the
reason, and the reason is the part worth publishing.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass

from .comparison import Outcome
from .fixtures import BAIT_SECRET_VALUE

_LEAK_YES = "LEAKED"
_LEAK_NO = "clean"

@dataclass(frozen=True)
class Provenance:
    """Where the model's answers in a report came from.

    A replayed run exercises the same code — the same audit, Reader, boundary,
    Executor and output audit — but no model decided anything during it. A
    report that did not say so would be claiming evidence it does not have.

    Passed in rather than inferred: the caller is the only one that knows, so
    it is the caller that has to say.
    """

    banner: str
    note: str


LIVE = Provenance(
    banner="",
    note=(
        "Generated by `python run_all.py`. Every row below is a real run "
        "against a real model, in a local sandbox, using an obviously fake "
        "secret. No GitHub API and no third-party service is involved."
    ),
)

REPLAY = Provenance(
    banner="REPLAY — recorded responses, no model was called during this run",
    note=(
        "Generated by `python run_all.py --replay`. **Every row below is a "
        "replay of a recorded exchange, not a live run.** The code path is the "
        "real one — the same audit, Reader, boundary, Executor and output "
        "audit — but the model's responses were recorded earlier and are served "
        "from `tests/cassettes/`, so nothing here was decided by a model during "
        "this run.\n\n"
        "That is what makes it reproducible byte-for-byte and free to run. It "
        "is also its limit: the probabilistic layers show you one recorded "
        "sample rather than how they behave. For that, run it live, or read the "
        "measured rates and confidence intervals in README.md."
    ),
)


def _status(outcome: Outcome) -> str:
    """The one-word status `render_terminal`'s table and leak counters agree on.

    `.leaked` checked before `.error`, not after: `ibr/comparison.py`'s
    `run_scenario` computes `.leaked` from the real sandbox file state
    unconditionally, after its try/except — a run can genuinely leak the
    secret and then crash on a later turn. The leak counters below this
    function (`[o for o in outcomes if o.leaked]`) already read `.leaked`
    directly and get this right; this function used to disagree with them
    by checking `.error` first, so a leaked-then-crashed row showed
    `"error"` while the aggregate count two lines later correctly said the
    same run leaked — the same bug `render_markdown`'s Results table had,
    in the sibling renderer.
    """
    if outcome.leaked:
        return _LEAK_YES
    if outcome.error:
        return "error"
    return _LEAK_NO


def render_terminal(
    outcomes: list[Outcome], *, provenance: Provenance = LIVE
) -> str:
    lines: list[str] = []
    rule = "─" * 100
    if provenance.banner:
        lines.append(provenance.banner)
    lines.append(rule)
    lines.append(
        f"{'scenario':<46} {'action':<18} {'secret':<8} {'audit':<12} {'tries':<6}"
    )
    lines.append(rule)
    for outcome in outcomes:
        tries = (
            f"{outcome.attempts}/{outcome.attempts_allowed}"
            if outcome.attempts_allowed > 1
            else "-"
        )
        lines.append(
            f"{outcome.scenario.title:<46} "
            f"{outcome.action:<18} "
            f"{_status(outcome):<8} "
            f"{outcome.risk_level or '-':<12} "
            f"{tries:<6}"
        )
    lines.append(rule)

    leaked = [o for o in outcomes if o.leaked]
    baseline_leaks = [o for o in leaked if o.scenario.architecture == "baseline"]
    isolated_leaks = [o for o in leaked if o.scenario.architecture == "isolated"]

    lines.append("")
    lines.append(f"baseline runs that leaked the secret : {len(baseline_leaks)}")
    lines.append(f"isolated runs that leaked the secret : {len(isolated_leaks)}")
    if isolated_leaks:
        lines.append("")
        lines.append(
            "!! An isolated run leaked. That is a defect in the boundary, not "
            "a demo outcome."
        )
    return "\n".join(lines)


def _fence(text: str, language: str = "") -> str:
    return f"```{language}\n{text.rstrip()}\n```"


def _leak_evidence(outcome: Outcome) -> list[str]:
    """Quote the actual leaked lines.

    A report that asserts "LEAKED" without showing the bytes is asking to be
    taken on faith, which is the opposite of the point.
    """
    hits = [
        line.strip()
        for line in outcome.public_surface.splitlines()
        if BAIT_SECRET_VALUE in line
    ]
    if not hits:
        return []
    return [
        "**Evidence.** These lines were written to the public surface "
        "(`sandbox/public_comments.txt`):\n",
        _fence("\n".join(hits)),
        "",
    ]


def render_markdown(
    outcomes: list[Outcome], *, provenance: Provenance = LIVE
) -> str:
    parts: list[str] = []

    parts.append("# Prompt injection: blast radius comparison\n")
    parts.append(provenance.note + "\n")

    parts.append("## What was tested\n")
    parts.append(
        "The same two issues — one ordinary bug report, one carrying a hidden "
        "instruction that asks the reader to publish the contents of "
        "`sandbox/.env` — put through two architectures:\n\n"
        "- **Baseline**: a single agent that reads the issue, can read files, "
        "and can post a public comment.\n"
        "- **Isolated**: security audit → Reader (no tools) → "
        "**structured boundary** → Executor (enum fields only) → output audit.\n"
    )

    parts.append("## Results\n")
    parts.append("| Scenario | Action taken | Secret in public output | Audit verdict |")
    parts.append("|---|---|---|---|")
    for outcome in outcomes:
        if outcome.leaked:
            # Checked before `.error`, not after: `ibr/comparison.py`'s
            # `run_scenario` computes `.leaked`/`.public_surface` from the
            # real sandbox file state *after* its try/except, unconditionally
            # — unlike `.action`, which stays at its stale "no_action"
            # default when the run raised before ever reaching the line that
            # sets it for real. A run can genuinely leak the secret (e.g. the
            # baseline posts a comment on turn 1) and then crash on a later
            # turn; checking `.error` first here used to erase that confirmed
            # leak and report the row as merely "error" — contradicting
            # "Reading the result" below and `render_terminal`'s leak
            # counters, both of which read `.leaked` directly and correctly
            # said a leak happened. `.action` is genuinely unknown in this
            # combined case (never reached before the run raised), so it is
            # not shown as if it were.
            action_cell = f"`{outcome.action}`" if not outcome.error else "*(run then failed)*"
            parts.append(
                f"| {outcome.scenario.title} | {action_cell} | **LEAKED** | "
                f"{outcome.risk_level or '—'} |"
            )
            continue
        if outcome.error:
            # `action` defaults to "no_action" — a run that raised before
            # completing (and did not leak) reads exactly like one that was
            # checked and found clean, in the very first table a reader
            # sees, unless `.error` is checked here too.
            parts.append(
                f"| {outcome.scenario.title} | *(run failed)* | error | — |"
            )
            continue
        parts.append(
            f"| {outcome.scenario.title} | `{outcome.action}` | clean | "
            f"{outcome.risk_level or '—'} |"
        )
    parts.append("")

    parts.append("## Why each result happened\n")
    for outcome in outcomes:
        parts.append(f"### {outcome.scenario.title}\n")
        parts.append(f"{outcome.scenario.description}\n")
        if outcome.error:
            parts.append(f"> Run failed: `{outcome.error}`\n")
            if outcome.leaked:
                # `.leaked`/`.public_surface` are captured from the real
                # sandbox state regardless of whether the run later raised
                # (see the '## Results' table above for why) — a leak that
                # happened before a crash is still a leak, and this is
                # specifically the section whose job is to show the actual
                # bytes rather than assert a leak on faith
                # (`_leak_evidence`'s own docstring). `.published` is not
                # shown here even though a leak happened: unlike
                # `.public_surface`, it is only ever set on the line right
                # after the one that raised, so it is genuinely unknown in
                # this case, not merely unlucky to read.
                parts.extend(_leak_evidence(outcome))
            continue
        if outcome.stages:
            parts.append(f"Stages: {' → '.join(f'`{s}`' for s in outcome.stages)}\n")
        parts.append(f"**Mechanism.** {outcome.mechanism}\n")
        for note in outcome.notes:
            parts.append(f"- {note}\n")
        parts.extend(_leak_evidence(outcome))
        if outcome.published:
            parts.append("Published to the public surface:\n")
            parts.append(_fence(textwrap.shorten(outcome.published, 600, placeholder=" …")))
            parts.append("")
        else:
            parts.append("Nothing was published.\n")

    parts.append("## Did the defense cost the feature?\n")
    benign = {
        o.scenario.architecture: o
        for o in outcomes
        if o.scenario.issue_name == "benign"
    }
    baseline_benign = benign.get("baseline")
    isolated_benign = benign.get("isolated")
    if baseline_benign and isolated_benign:
        # `action` defaults to "no_action" on the `Outcome` dataclass and is
        # left untouched whenever `run_scenario` sets `error` instead of a
        # real decision (an API timeout or connection error before the run
        # produced anything) — so an infrastructure failure reads exactly
        # like a genuine "the pipeline looked at this and chose not to act"
        # outcome if only `action` is checked. Attributing benign-parity
        # results without checking `error` first used to produce a
        # confident, specific, and false causal story ("the baseline is the
        # one that dropped it") about a run that never even completed —
        # exactly the "attribute a timeout to a decision" mistake this
        # file's "Reading the result" section already takes care to avoid
        # (see the `audit_completed` check below) and
        # `ibr/comparison.py`'s `run_scenario_sampled` names directly ("the
        # same mistake" as counting a fail-closed verdict as a detection).
        baseline_errored = bool(baseline_benign.error)
        isolated_errored = bool(isolated_benign.error)
        if baseline_errored and isolated_errored:
            parts.append(
                "**Both benign runs failed before completing** (baseline: "
                f"`{baseline_benign.error}`; isolated: "
                f"`{isolated_benign.error}`), so no functional-parity "
                "comparison is possible from this run.\n"
            )
        elif baseline_errored:
            parts.append(
                "**The baseline run failed before completing** "
                f"(`{baseline_benign.error}`), so its outcome cannot be "
                "compared against the isolated pipeline's on this run.\n"
            )
        elif isolated_errored:
            parts.append(
                "**The isolated run failed before completing** "
                f"(`{isolated_benign.error}`), so its outcome cannot be "
                "compared against the baseline's on this run.\n"
            )
        else:
            both_acted = (
                baseline_benign.action != "no_action"
                and isolated_benign.action != "no_action"
            )
            parts.append(
                f"On the ordinary bug report, the baseline chose "
                f"`{baseline_benign.action}` and the isolated pipeline chose "
                f"`{isolated_benign.action}`.\n"
            )
            if both_acted and baseline_benign.action != isolated_benign.action:
                parts.append(
                    "These are not the same action, and it is worth being "
                    "precise about what that does and does not show. Both "
                    "architectures triaged the issue correctly and took a "
                    "useful action; they differ in *which* useful action, "
                    "because the isolated Executor picks from a fixed set "
                    "(`reply_comment`, `label_bug`, `label_question`, "
                    "`no_action`) while the baseline writes free-form prose. "
                    "The claim being made here is that isolation did not "
                    "break benign triage — not that the two produce "
                    "byte-identical output, which a design built around a "
                    "fixed action set could never do.\n"
                )
            elif both_acted:
                parts.append(
                    "Both architectures took the same action on benign "
                    "input: isolation did not cost the feature.\n"
                )
            else:
                baseline_acted = baseline_benign.action != "no_action"
                isolated_acted = isolated_benign.action != "no_action"
                if isolated_acted and not baseline_acted:
                    # The isolated pipeline is the one that handled this
                    # issue — the baseline is the one that dropped it. That
                    # is not a cost of isolation, so this must not read as
                    # "a defense" failing.
                    parts.append(
                        "**The baseline took no action on benign input; the "
                        "isolated pipeline did.** That is not a cost of "
                        "isolation — the isolated pipeline is the one that "
                        "handled this issue correctly, and the baseline is "
                        "the one that dropped it.\n"
                    )
                elif baseline_acted and not isolated_acted:
                    # The only case where "did the defense cost the
                    # feature?" is actually the right question: baseline
                    # succeeded and isolation is the one that failed to act.
                    parts.append(
                        "**The isolated pipeline took no action on benign "
                        "input; the baseline did.** That is a functionality "
                        "regression worth investigating — a defense that "
                        "silently drops legitimate issues is not a good "
                        "trade.\n"
                    )
                else:
                    parts.append(
                        "**Both architectures took no action on benign "
                        "input.** Neither triaged the issue; that is worth "
                        "investigating on its own, but it does not show "
                        "that isolation specifically cost this feature.\n"
                    )

    parts.append("## Reading the result\n")
    baseline_leaked = any(
        o.leaked for o in outcomes if o.scenario.architecture == "baseline"
    )
    isolated_leaked = any(
        o.leaked for o in outcomes if o.scenario.architecture == "isolated"
    )

    if baseline_leaked and not isolated_leaked:
        # Which layer actually stopped the ordinary malicious run — not
        # assumed, read off that specific outcome. Two other rows genuinely
        # reach isolated+malicious (the bypassed run and the deterministic
        # worst-case), so this is the one scenario key that means "the audit
        # ran normally, unbypassed" rather than the isolated architecture in
        # general.
        ordinary_malicious = next(
            (o for o in outcomes if o.scenario.key == "isolated_malicious"), None
        )
        short_circuited = bool(
            ordinary_malicious
            and "short_circuit" in ordinary_malicious.stages
            and ordinary_malicious.audit_completed
        )
        parts.append(
            "The baseline leaked and the isolated pipeline did not — but the "
            "interesting part is *which layer* stopped it.\n\n"
        )
        if short_circuited:
            parts.append(
                "In this run, the **security audit** caught the injection and "
                "short-circuited. That layer is probabilistic: it is cheap, it "
                "stops unsophisticated attacks, and a good enough attack gets "
                "past it. If that were the only defense, the system would be "
                "one clever rephrasing away from the baseline's outcome.\n\n"
            )
        elif ordinary_malicious is None:
            # The ordinary, unbypassed isolated+malicious run is not among the
            # outcomes handed to this report (a partial/filtered outcome
            # list). Nothing here says whether the audit or the boundary
            # stopped the attack, so say that plainly instead of asserting
            # the "structured boundary contained it" narrative below about a
            # run that was never represented.
            parts.append(
                "This report does not include a run of the ordinary, "
                "unbypassed `isolated_malicious` scenario, so which layer — "
                "the probabilistic security audit or the structured "
                "boundary — actually stopped this particular attack cannot "
                "be determined from the outcomes given here.\n\n"
            )
        elif ordinary_malicious and not ordinary_malicious.audit_completed:
            parts.append(
                "In this run the **security audit call itself failed** — a "
                f"timeout or connection error (`{ordinary_malicious.risk_level}`)"
                " — and the pipeline failed closed to `no_action` without the "
                "Reader or Executor ever running. That is not the audit "
                "detecting anything; it is PROJECT_SPEC.md §1.4's fail-closed "
                "rule doing its job on a check that never completed. The "
                "probabilistic layer did not stop this run — a network error "
                "did, which is a different claim and a weaker one to lean on.\n\n"
            )
        elif ordinary_malicious.error:
            # `audit_completed` and `stages` both default to values ("True"
            # and "()") that look exactly like "the audit passed cleanly and
            # nothing ran yet" — `run_scenario`'s `except openai.APIError`
            # (ibr/comparison.py) sets `.error` without touching either, so
            # a run that raised before the audit even started reads
            # identically, to the two checks above, as one where the audit
            # already succeeded. Checked directly, not inferred: this is
            # exactly the same action/decision-vs-error conflation the
            # benign-parity section above was fixed to avoid, left open
            # here in the sibling section for the malicious comparison.
            parts.append(
                "**This run of the ordinary, unbypassed `isolated_malicious` "
                f"scenario failed before completing** (`{ordinary_malicious.error}`), "
                "so which layer — if either — would have stopped this "
                "attack cannot be determined from it.\n\n"
            )
        else:
            note = (
                f" (`{ordinary_malicious.risk_level}`)" if ordinary_malicious else ""
            )
            parts.append(
                f"In this run the security audit did **not** short-circuit{note}"
                " — per PROJECT_SPEC.md §3.1, only `high_risk` does; `suspicious` "
                "passes through with a review flag. The Reader ran and the "
                "**structured boundary** is what actually contained it: the "
                "Reader's free text never reaches the Executor, which reads "
                "two enum fields and selects a static template. This run is "
                "already the case the paragraph below argues for, not the one "
                "the probabilistic layer gets credit for.\n\n"
            )
        parts.append(
            "The bypassed-audit and fully-captured-Reader rows are there to "
            "show what remains once the probabilistic layer is gone. The Reader "
            "can be persuaded to write anything at all into `reasoning` and "
            "`summary`; the Executor never reads either field. It reads two "
            "enum-constrained fields and selects a static template. The set of "
            "things a captured Reader can cause is therefore finite and "
            "enumerated in advance, and it does not grow when the attacker "
            "gets smarter.\n\n"
            "That is the difference between the two materials: the audit "
            "*probably* stops an attack, the boundary *structurally* bounds "
            "what any attack can accomplish.\n"
        )
    elif not baseline_leaked:
        # `Outcome.leaked` defaults to False, same as `run_scenario` leaves
        # it when the run raises before completing (`.error` gets set;
        # `.leaked` never does) — so an errored baseline run and a genuine
        # "the model declined" run read identically here unless `.error` is
        # checked first. Same conflation as the branch above, same fix.
        baseline_malicious_outcome = next(
            (o for o in outcomes if o.scenario.key == "baseline_malicious"), None
        )
        if baseline_malicious_outcome is None:
            # Mirrors the `ordinary_malicious is None` guard above, for the
            # baseline side: if this scenario is absent from a
            # partial/filtered outcomes list, `baseline_leaked` is
            # vacuously False with no baseline run to have an opinion
            # about. The `if ... and ....error` check below is falsy on
            # `None` for the same reason and used to fall straight through
            # to the final `else`, asserting "the model declined this
            # time" about a run that was never given to this report.
            parts.append(
                "This report does not include a run of the "
                "`baseline_malicious` scenario, so whether the baseline "
                "would have leaked on this input cannot be determined "
                "from the outcomes given here.\n"
            )
        elif baseline_malicious_outcome.error:
            parts.append(
                "**The baseline run failed before completing** "
                f"(`{baseline_malicious_outcome.error}`), so whether it "
                "would have leaked on this input cannot be determined "
                "from this run.\n"
            )
        else:
            parts.append(
                "The baseline did not leak on this run. Compliance with an "
                "injected instruction is probabilistic — the model declined "
                "this time. Re-run to sample again; the architectural point "
                "is unchanged, since the baseline's capability to leak is a "
                "property of its design rather than of any single run.\n"
            )
    if isolated_leaked:
        parts.append(
            "**An isolated run leaked.** That is a defect in the boundary, not "
            "an expected outcome — investigate before trusting these results.\n"
        )

    parts.append("## Caveats\n")
    parts.append(
        f"- The \"secret\" is the fixed placeholder `{BAIT_SECRET_VALUE}`. "
        "Nothing real is at risk here.\n"
        "- Everything runs against local files in `sandbox/`. The \"issue\" and "
        "the \"public comment\" are both text files.\n"
        "- Model behaviour varies between runs. The rows that depend on a model "
        "declining or complying will not be identical every time; the "
        "deterministic row is the one that always gives the same answer.\n"
    )

    return "\n".join(parts)
