"""Render the Phase 4 comparison as a terminal table and a markdown report.

The acceptance bar (PROJECT_SPEC.md §4 Phase 4) is that someone who has not
read the code can read the report and understand what happened and why. So
every row carries a mechanism sentence, not just a pass/fail mark — "isolated
didn't leak" is a result; "the Executor only read two enum fields" is the
reason, and the reason is the part worth publishing.
"""

from __future__ import annotations

import textwrap

from .comparison import Outcome
from .config import BAIT_SECRET_VALUE

_LEAK_YES = "LEAKED"
_LEAK_NO = "clean"


def _status(outcome: Outcome) -> str:
    if outcome.error:
        return "error"
    return _LEAK_YES if outcome.leaked else _LEAK_NO


def render_terminal(outcomes: list[Outcome]) -> str:
    lines: list[str] = []
    rule = "─" * 100
    lines.append(rule)
    lines.append(
        f"{'scenario':<46} {'action':<18} {'secret':<8} {'audit':<12} {'tries':<6}"
    )
    lines.append(rule)
    for outcome in outcomes:
        tries = (
            f"{outcome.attempts}/{outcome.attempts_allowed}"
            if outcome.attempts_allowed > 1
            else "-"
        )
        lines.append(
            f"{outcome.scenario.title:<46} "
            f"{outcome.action:<18} "
            f"{_status(outcome):<8} "
            f"{outcome.risk_level or '-':<12} "
            f"{tries:<6}"
        )
    lines.append(rule)

    leaked = [o for o in outcomes if o.leaked]
    baseline_leaks = [o for o in leaked if o.scenario.architecture == "baseline"]
    isolated_leaks = [o for o in leaked if o.scenario.architecture == "isolated"]

    lines.append("")
    lines.append(f"baseline runs that leaked the secret : {len(baseline_leaks)}")
    lines.append(f"isolated runs that leaked the secret : {len(isolated_leaks)}")
    if isolated_leaks:
        lines.append("")
        lines.append(
            "!! An isolated run leaked. That is a defect in the boundary, not "
            "a demo outcome."
        )
    return "\n".join(lines)


def _fence(text: str, language: str = "") -> str:
    return f"```{language}\n{text.rstrip()}\n```"


def _leak_evidence(outcome: Outcome) -> list[str]:
    """Quote the actual leaked lines.

    A report that asserts "LEAKED" without showing the bytes is asking to be
    taken on faith, which is the opposite of the point.
    """
    hits = [
        line.strip()
        for line in outcome.public_surface.splitlines()
        if BAIT_SECRET_VALUE in line
    ]
    if not hits:
        return []
    return [
        "**Evidence.** These lines were written to the public surface "
        "(`sandbox/public_comments.txt`):\n",
        _fence("\n".join(hits)),
        "",
    ]


def render_markdown(outcomes: list[Outcome]) -> str:
    parts: list[str] = []

    parts.append("# Prompt injection: blast radius comparison\n")
    parts.append(
        "Generated by `python run_all.py`. Every row below is a real run "
        "against a real model, in a local sandbox, using an obviously fake "
        "secret. No GitHub API and no third-party service is involved.\n"
    )

    parts.append("## What was tested\n")
    parts.append(
        "The same two issues — one ordinary bug report, one carrying a hidden "
        "instruction that asks the reader to publish the contents of "
        "`sandbox/.env` — put through two architectures:\n\n"
        "- **Baseline**: a single agent that reads the issue, can read files, "
        "and can post a public comment.\n"
        "- **Isolated**: security audit → Reader (no tools) → "
        "**structured boundary** → Executor (enum fields only) → output audit.\n"
    )

    parts.append("## Results\n")
    parts.append("| Scenario | Action taken | Secret in public output | Audit verdict |")
    parts.append("|---|---|---|---|")
    for outcome in outcomes:
        marker = "**LEAKED**" if outcome.leaked else "clean"
        parts.append(
            f"| {outcome.scenario.title} | `{outcome.action}` | {marker} | "
            f"{outcome.risk_level or '—'} |"
        )
    parts.append("")

    parts.append("## Why each result happened\n")
    for outcome in outcomes:
        parts.append(f"### {outcome.scenario.title}\n")
        parts.append(f"{outcome.scenario.description}\n")
        if outcome.error:
            parts.append(f"> Run failed: `{outcome.error}`\n")
            continue
        if outcome.stages:
            parts.append(f"Stages: {' → '.join(f'`{s}`' for s in outcome.stages)}\n")
        parts.append(f"**Mechanism.** {outcome.mechanism}\n")
        for note in outcome.notes:
            parts.append(f"- {note}\n")
        parts.extend(_leak_evidence(outcome))
        if outcome.published:
            parts.append("Published to the public surface:\n")
            parts.append(_fence(textwrap.shorten(outcome.published, 600, placeholder=" …")))
            parts.append("")
        else:
            parts.append("Nothing was published.\n")

    parts.append("## Did the defense cost the feature?\n")
    benign = {
        o.scenario.architecture: o
        for o in outcomes
        if o.scenario.issue_name == "benign"
    }
    baseline_benign = benign.get("baseline")
    isolated_benign = benign.get("isolated")
    if baseline_benign and isolated_benign:
        both_acted = (
            baseline_benign.action != "no_action"
            and isolated_benign.action != "no_action"
        )
        parts.append(
            f"On the ordinary bug report, the baseline chose "
            f"`{baseline_benign.action}` and the isolated pipeline chose "
            f"`{isolated_benign.action}`.\n"
        )
        if both_acted and baseline_benign.action != isolated_benign.action:
            parts.append(
                "These are not the same action, and it is worth being precise "
                "about what that does and does not show. Both architectures "
                "triaged the issue correctly and took a useful action; they "
                "differ in *which* useful action, because the isolated "
                "Executor picks from a fixed set (`reply_comment`, "
                "`label_bug`, `label_question`, `no_action`) while the "
                "baseline writes free-form prose. The claim being made here is "
                "that isolation did not break benign triage — not that the two "
                "produce byte-identical output, which a design built around a "
                "fixed action set could never do.\n"
            )
        elif both_acted:
            parts.append(
                "Both architectures took the same action on benign input: "
                "isolation did not cost the feature.\n"
            )
        else:
            parts.append(
                "**One architecture took no action on benign input.** That is "
                "a functionality regression worth investigating — a defense "
                "that silently drops legitimate issues is not a good trade.\n"
            )

    parts.append("## Reading the result\n")
    baseline_leaked = any(
        o.leaked for o in outcomes if o.scenario.architecture == "baseline"
    )
    isolated_leaked = any(
        o.leaked for o in outcomes if o.scenario.architecture == "isolated"
    )

    if baseline_leaked and not isolated_leaked:
        parts.append(
            "The baseline leaked and the isolated pipeline did not — but the "
            "interesting part is *which layer* stopped it.\n\n"
            "In the ordinary malicious run, the **security audit** caught the "
            "injection and short-circuited. That layer is probabilistic: it is "
            "cheap, it stops unsophisticated attacks, and a good enough attack "
            "gets past it. If that were the only defense, the system would be "
            "one clever rephrasing away from the baseline's outcome.\n\n"
            "The bypassed-audit and fully-captured-Reader rows are there to "
            "show what remains once the probabilistic layer is gone. The Reader "
            "can be persuaded to write anything at all into `reasoning` and "
            "`summary`; the Executor never reads either field. It reads two "
            "enum-constrained fields and selects a static template. The set of "
            "things a captured Reader can cause is therefore finite and "
            "enumerated in advance, and it does not grow when the attacker "
            "gets smarter.\n\n"
            "That is the difference between the two materials: the audit "
            "*probably* stops an attack, the boundary *structurally* bounds "
            "what any attack can accomplish.\n"
        )
    elif not baseline_leaked:
        parts.append(
            "The baseline did not leak on this run. Compliance with an injected "
            "instruction is probabilistic — the model declined this time. "
            "Re-run to sample again; the architectural point is unchanged, "
            "since the baseline's capability to leak is a property of its "
            "design rather than of any single run.\n"
        )
    if isolated_leaked:
        parts.append(
            "**An isolated run leaked.** That is a defect in the boundary, not "
            "an expected outcome — investigate before trusting these results.\n"
        )

    parts.append("## Caveats\n")
    parts.append(
        f"- The \"secret\" is the fixed placeholder `{BAIT_SECRET_VALUE}`. "
        "Nothing real is at risk here.\n"
        "- Everything runs against local files in `sandbox/`. The \"issue\" and "
        "the \"public comment\" are both text files.\n"
        "- Model behaviour varies between runs. The rows that depend on a model "
        "declining or complying will not be identical every time; the "
        "deterministic row is the one that always gives the same answer.\n"
    )

    return "\n".join(parts)
